/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.main.view;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.*;


/**
 *
 * @author RUKHSAR-JAMADAR
 */
public class doctor_form extends javax.swing.JFrame {
       static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";          //declaration of static variable JDBC_DRIVER and value initialized to it
    static final String DB_URL = "jdbc:mysql://localhost:3307/db_hospital"; //declaration of static variable DB_URL,databse path initialized to it
    //Database Credentials
    static final String USER = "root";                                  //declaration of static variable USER and value initialized to it
    static final String PASS = "";
    static Connection conn;
    static PreparedStatement pst=null;
    



    /**
     * Creates new form doctor_form
     */
    public doctor_form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        name_f = new javax.swing.JTextField();
        splt_f = new javax.swing.JTextField();
        tmg_f = new javax.swing.JTextField();
        qn_f = new javax.swing.JTextField();
        rno_f = new javax.swing.JTextField();
        submit_btn = new javax.swing.JButton();
        cancel_btn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Name:");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Specilist:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Timing:");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Qualification");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Room_No:");
        jLabel6.setToolTipText("");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        name_f.setText("jTextField1");
        getContentPane().add(name_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        splt_f.setText("jTextField2");
        getContentPane().add(splt_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        tmg_f.setText("jTextField3");
        getContentPane().add(tmg_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        qn_f.setText("jTextField4");
        getContentPane().add(qn_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        rno_f.setText("jTextField5");
        getContentPane().add(rno_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        submit_btn.setBackground(new java.awt.Color(0, 255, 0));
        submit_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submit_btn.setText("SUBMIT");
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });
        getContentPane().add(submit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        cancel_btn.setBackground(new java.awt.Color(204, 0, 0));
        cancel_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancel_btn.setText("CANCEL");
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });
        getContentPane().add(cancel_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 204));
        jLabel7.setText("Add The Details");
        jLabel7.setToolTipText("");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed
        // TODO add your handling code here:
        try
        {
         Class.forName(JDBC_DRIVER);
         conn=DriverManager.getConnection(DB_URL,USER,PASS);
         String name=name_f.getText().toString();
         String specilist=splt_f.getText().toString();
         String time=tmg_f.getText().toString();
         String qualification=qn_f.getText().toString();
         String  r_no=rno_f.getText().toString();
         name_f.setText(name);
         splt_f.setText(specilist);
         tmg_f.setText(time);
         qn_f.setText(qualification);
         rno_f.setText(r_no);
         String q="INSERT INTO `doctor_tbl`( `name`, `specilist`, `timing`, `qualification`, `room_no`) VALUES ('"+name+"','"+specilist+"','"+time+"','"+qualification+"','"+r_no+"') ";
        pst=conn.prepareStatement(q);
        pst.executeUpdate(q);
        JOptionPane.showMessageDialog(null,"Doctor deatils recorded Sucessfully!!");

        }
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(null,e);  
        }
    }//GEN-LAST:event_submit_btnActionPerformed

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        // TODO add your handling code here:
         name_f.setText(null);
         splt_f.setText(null);
         tmg_f.setText(null);
         qn_f.setText(null);
         rno_f.setText(null);
    }//GEN-LAST:event_cancel_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(doctor_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(doctor_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(doctor_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(doctor_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new doctor_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_btn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField name_f;
    private javax.swing.JTextField qn_f;
    private javax.swing.JTextField rno_f;
    private javax.swing.JTextField splt_f;
    private javax.swing.JButton submit_btn;
    private javax.swing.JTextField tmg_f;
    // End of variables declaration//GEN-END:variables
}
